# Generated by Django 3.2.6 on 2021-08-29 17:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='followers',
            field=models.ManyToManyField(related_name='_users_customuser_followers_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
