name: Testing
on: push

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@2
    - name: Run Django unit test
      run: | 
        pip3 install --user django
        python3 manage.py test network.test_server users